# -*- coding: utf-8 -*-
"""banner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RNJTMUuVlWrsDy8JRA-38YtHgIDpEfG
"""

import socket  
import requests  
from scapy.all import sniff
capture=sniff(count=1)
capture.summary()
host= input("enter url:")
ip=socket.gethostbyname(host)
print("Hostname=",host,"\tIP-->",ip)
def banner(ip,port):
  s=socket.socket()
  s.connect((ip,int(port)))
  print(s.recv(100))
port=str(input("Enter the port number:"))
banner(ip,port)
print(host)
#check if vulnerable
domain = "https://www."+host
headers= requests.get(domain).headers

if 'X-Frame-Options' in headers:
    print(domain," non - vulnerable")
else:
    print(domain, " vulnerable")

!pip install scapy